title: Bingyu Zhang
keywords: "Bingyu, bingyu, Bingyu Zhang, Bingyu Zhang math, bingyu Zhang, bingyu Zhang math, Bingyu Zhang odense, bingyu Zhang odense, 张秉宇"
description: University of Southern Denmark
url: https://byzhang.cn/
markdown: kramdown

theme: jekyll-theme-cayman
